name: book_shop_admin_panel
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  animated_floating_buttons: ^0.0.2
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.9
  dartz: ^0.10.1
  data_connection_checker_tv: ^0.3.5-nullsafety
  dio: ^4.0.6
  dropdown_button2: ^2.0.0
  equatable: ^2.0.0
  filepicker_windows: ^2.0.0
  flare_loading: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0
  flutter_rating_bar: ^4.0.0
  flutter_slidable: 1.1.0
  fluttertoast: ^8.0.6
  get_it: ^7.2.0
  http: ^0.13.1
  intl: ^0.18.0
  json_annotation: ^4.7.0
  motion_toast: ^2.6.6
  octo_image: ^1.0.2
  oktoast: ^3.0.0
  path_provider: ^2.0.14
  persian_number_utility: ^1.1.3
  progress_state_button: ^1.0.3
  progressive_image: ^2.0.1
  retrofit: ^3.3.1
  shared_preferences: ^2.0.11
  simple_animations: 4.0.1
  sizer: ^2.0.15
  supercharged: ^2.1.1
  web_socket_channel: ^2.3.0

dev_dependencies:
  build_runner: ^2.3.0

  flutter_lints: 1.0.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.5.1
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/add_1.png
    - assets/images/edit_pen_1.png
    - assets/images/search_1.png
    - assets/images/delete_1.png
    - assets/images/auction_1.png
    - assets/images/dish_1.png
    - assets/images/hourglass_1.png
    - assets/images/lab_tool_1.png
    - assets/images/medicine_1.png
    - assets/images/trophy_1.png
    - assets/images/image_1.png
    - assets/images/attention_128_1.png
    - assets/images/image_2.png
    - assets/images/user_ico.png
    - assets/images/circle_1.png
    - assets/images/circle_2.png
    - assets/images/circle_3.png
    - assets/images/circle_4.png
    - assets/images/mobile/circle_1.png
    - assets/images/mobile/circle_2.png
    - assets/images/mobile/circle_3.png
    - assets/images/mobile/circle_4.png
    - assets/images/empty.png
    - assets/flare/loading_book.flr
    - assets/flare/book_dropping.flr
    - assets/flare/no_network.flr
    - assets/flare/cosmos.flr
    - assets/images/customer_agent.png
    - assets/images/book_place_holder.png
    - assets/images/attention_small.png
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iran_sans/iran_sans_mobile.ttf
        - asset: assets/fonts/iran_sans/iran_sans_mobile_black.ttf
          weight: 900
        - asset: assets/fonts/iran_sans/iran_sans_mobile_bold.ttf
          weight: 800
        - asset: assets/fonts/iran_sans/iran_sans_mobile_black.ttf
          weight: 700
        - asset: assets/fonts/iran_sans/iran_sans_mobile_medium.ttf
          weight: 500
        - asset: assets/fonts/iran_sans/iran_sans_mobile.ttf
          weight: 400
        - asset: assets/fonts/iran_sans/iran_sans_mobile_light.ttf
          weight: 300
        - asset: assets/fonts/iran_sans/iran_sans_mobile_ultra_light.ttf
          weight: 200
